database=postgres
db.project = ${POSTGRES_DB_PROJECT}
db.project = ${POSTGRES_DB_SERVER}
db.project = ${POSTGRES_DB_NAME}
db.project = ${POSTGRES_DB_USER}
db.project = ${POSTGRES_DB_PASS}
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql:///${db.name}?cloudSqlInstance=${db.project}>us-central1:${db.server}&socketFactory=com/google.cloud.sql.postgres.socketFactory&user=${db.user}&password{db.pw}&useSSL=false}
